\context ChordNames
	\chords {
		\set chordChanges = ##t
		% intro
		e2:m d4. e8:m ~ e1:m

		% cordero de dios...
		e2:m d4. e8:m ~ e2:m d2
		c4. d8 ~ d2 e8:m e8:m r4 r2

		% ten piedad de nosotros...
		c1 g1 b1:7

		% cordero de dios...
		e2:m d4. e8:m ~ e2:m d2
		c4. d8 ~ d2 e8:m e8:m r4 r2

		% ten piedad de nosotros...
		c1 g1 b1:7

		% cordero de dios...
		e2:m d4. e8:m ~ e2:m d2
		c4. d8 ~ d2 e8:m e8:m r4 r2

		% danos la paz...
		c2 d2 e1:m
		c2 d2 e1
	}
